### ISSUE TITLE
api からの annealing でエラーになる

### ISSUE THREAD

**Issue by ishikawakouji** [Blueqat/bqcloud#16]
blueqat のクラウド環境において、このリポジトリのサンプルを参考にアニーリングを実行すると、エラーが発生します。
しかし、ジョブは投げられており、blueqat の API key のページで参照すると、結果が戻ってきています。

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-1-5d697e0d56f1> in <module>
>       1 import bqcloud
>       2 api = bqcloud.load_api()
> ----> 3 api.annealing([[-1, 0], [0, 0.5]], 5, 10)
> 
> /opt/conda/lib/python3.9/site-packages/bqcloud/api.py in annealing(self, qubo, chain_strength, num_reads)
>      79             "num_reads": num_reads
>      80         })
> ---> 81         return AnnealingResult(**res)
>      82 
>     83     def execute(self,
> 
> TypeError: __init__() got an unexpected keyword argument 'task'

**Comment by gyu-don** [comment]
bqcloudを最新版にアップデートしてください。

`pip install -U blueqat-cloud`

**Comment by ishikawakouji** [comment]
カーネルを再起動して、アップデートすることで正常になりました。
